version: '3'

services:
  database:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/mysql
    environment:
      mysql_user: root
      mysql_root_password: password
      mysql_database: global
